### ISSUE TITLE
Graceful container stopping

### ISSUE THREAD

**Issue by jest** [Microsoft/mssql-docker#171]
On Linux, using Docker CLI it is not possible to gracefully stop the container. Running `docker stop` causes the daemon to send TERM signal to the container process, which is ignored and only KILL signal causes the server to stop. However, this is abrupt and the next time the container is started it rolls forward logs.

However, I noticed that the main container process forks additional `sqlservr` processes and if I send TERM signal to one of those processes, the whole container shuts down gracefully immediately and no log replaying is performed on the next startup.

It is looks like the problem with the process and signals management.

**Comment by SokoMishaLov** [comment]
+1

**Comment by Glideh** [comment]
This simple container runs successfully:

```yml
version: '3'
services:
    db:
        image: microsoft/mssql-server-linux
        environment:
            ACCEPT_EULA: Y
            SA_PASSWORD: "xyz"
```

But can't be stopped

```
$ docker-compose stop db
ERROR: for my_db_1  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=70)
ERROR: An HTTP request took too long to complete. Retry with --verbose to obtain debug information.
If you encounter this issue regularly because of slow network conditions, consider setting COMPOSE_HTTP_TIMEOUT to a higher value (current value: 60).
```

Nor killed

```
$ docker-compose kill db
# Same timeout error

$ docker-compose kill -s TERM db
# Gets stuck
```

I even can't stop the docker service anymore.

**Comment by Glideh** [comment]
Work after a computer restart but it happened again.
A running mssql container doesn't seem liking to be updated with `up`

**Comment by Symbianx** [comment]
I've been having this issue too, the container freezes and a computer restart is the only way to stop it.

**Comment by edsonmedina** [comment]
+1 Same here

**Comment by helenwilliamson** [comment]
+1 Same here.

**Comment by akas84bg** [comment]
+1 same here

**Comment by twright-msft** [comment]
We think what's going on here is that SQL Server is gracefully shutting down so that when it starts back up there is no recovery time needed.  We could change it to a fast shut down on CTRL+C but that could mean a longer period of time for recovery on start up depending on what was going on in the database(s) prior to the CTRL+C.

I used to run into this issue too, but then I stopped running docker-compose up and docker run interactively.  In other words use -d on docker run and docker-compose up so that the containers are always started in the background and you can get your terminal prompt back.  Then you can stop your containers with docker stop or docker-compose down.

Also, when you use CTRL+C to a docker-compose up interactive, you can hit CTRL+C again to force stopping immediately.  I don't recommend that in anything except for a dev/test environment where you just don't care.

A few questions to better help us understand how to improve here:

- How long are you waiting after CTRL+C before you do a more drastic shutdown?
- Is there a lot of activity going on in the database before you CTRL+C - like a perf/scale test run or something like that?
- Do you have a general preference of fast shutdown/slow startup vs. slow shutdown/fast startup?

**Comment by jest** [comment]
Sorry, but this is not a graceful shutdown. No matter how much `time` is given with `docker stop -t time`, SQL Server never stops within this time period.

It has nothing to do with CTRL+C, I never used it. My containers are started with `docker-compose up -d` and stopped with `docker-compose stop -t time`.

Please also note what I have written about sending TERM signal to one of forked processes: it leads to gracefully stopped container within 1 second! If I were to guess, I'd go for checking correct signal handling in the parent process.

**Comment by Glideh** [comment]
I didn't use `Ctrl+C` either (the first one is supposed to gracefully shutdown anyway)
I'm also using `docker-compose stop` with really nothing big going on the database (tested with only one database and 4 tables actually).

@twright-msft I used to start/stop many different services (like nginx, apache, php, python, mysql, postgresql, redis, etc...), they always stop gracefully within 1/2sec max.
I might still have a preference for the fast startup/slow shutdown but the slow should be within 4sec.
Anyway, as @jest says, sometimes it never stops, I already tried leaving the graceful stop running for at least 30min.

**Comment by edsonmedina** [comment]
I've seen both cases, both intermittently. 

Using `CRTL + C` works sometimes, but every few other times it just hangs forever (I've waited more than 10 minutes) and the container becomes non-responsive (can't `exec` into it).

Using `docker-compose stop/down` instead returns me a timeout. The container never dies.

**Comment by jest** [comment]
OK, I dig a bit and here's a solution.

The problem is this line in `Dockerfile`

    CMD /opt/mssql/bin/sqlservr

According to [the Docker docs](https://docs.docker.com/engine/reference/builder/#cmd) its "shell syntax" causes Docker daemon to run the container with a command:

   /bin/sh -c /opt/mssql/bin/sqlservr

Which makes Bash a "PID 1" process and causes a lot of problems, including signal handling and children reaping. [The issue on tini](https://github.com/krallin/tini/issues/8) describes it pretty well.

The solution is to modify `Dockerfile` and either to make `sqlservr` "PID 1" itself using another `CMD` syntax:

    CMD ["/opt/mssql/bin/sqlservr"]

or better yet, to use some other "process manager", like the mentioned tini:

    # with tini next to Dockerfile...
    COPY tini /
    RUN chmod +x /tini
    ENTRYPOINT ["/tini", "--"]
    CMD ["/opt/mssql/bin/sqlservr"]

As a workaround till new images are available, use `command: [ "/opt/mssql/bin/sqlservr" ]` in your `docker-compose.yml` to overwrite the image's `CMD`.

**Comment by jest** [comment]
@twright-msft Any idea how this will be solved? Do you need a PR?

**Comment by woylie** [comment]
Any news on this? We're using the container for testing in a CI pipeline and have to restart our server practically every day because of this. Neither overwriting the command with `CMD ["/opt/mssql/bin/sqlservr"]` nor adding tini as suggested help with the problem.

**Comment by twright-msft** [comment]
We're likely going to switch to this in a near future release.  `CMD ["/opt/mssql/bin/sqlservr"]`

**Comment by woylie** [comment]
Well, for us it didn't. Any more ideas?

**Comment by jest** [comment]
Probably other issue?

**Comment by simdevmon** [comment]
The workaround `command: [ "/opt/mssql/bin/sqlservr" ]` did not work for me either.

**Comment by simdevmon** [comment]
I use the following workaround in our CI environment:

- I use the option `command: [ "/opt/mssql/bin/sqlservr" ]` in docker compose
- I just kill the process before I call docker-compose stop: `docker exec <container-name> kill 1 || :`

**Comment by jest** [comment]
Did you destroy the old containers and created new ones with `command:` workaround? Once created, containers can't change their command to be executed. What does `docker inspect -f '{{ .Config.Cmd }}' <container-names>` says?

**Comment by simdevmon** [comment]
@jest 
The output is `[/opt/mssql/bin/sqlservr]`

And yes, since it is only a CI environment I destroy everything completly on each build
```
docker exec <mssql-container-name> kill 1 || :
docker-compose stop
docker-compose rm -f
docker-compose build
docker-compose up -d
```

**Comment by kevin-brown** [comment]
We started running into issues with the MS SQL Server containers hanging around on our Jenkins instance after builds completed (or didn't). It eventually got bad enough that the servers would lock up and de-provisioning them would take up to 30 minutes.

The solution for killing process 1 seems to solve the issue for us: https://github.com/Microsoft/mssql-docker/issues/171#issuecomment-362193062

**Comment by jest** [comment]
@kevin-brown So this issue is not the one you are experiencing. This issue is about wrong image's `CMD` construction, where signals are not propagated to child processes.

Sending signals directly to child processes is the same as correcting `CMD` in Dockerfile.

**Comment by hdimitriou** [comment]
@kevin-brown we are facing probably the same issue and we use tini but no luck.
Do you believe that "-g" option on tini to kill the whole process group could make a difference? We are going to try it

**Comment by kevin-brown** [comment]
> So this issue is not the one you are experiencing. This issue is about wrong image's CMD construction, where signals are not propagated to child processes.

We're seeing signs of the signals not propagating when we send them to the Docker images, and attempt to send them directly to the process. The behaviour we're seeing in #181 is making it _really difficult_ to verify the signals are making it to `sqlservr` because if it hangs for too long it completely locks up Docker and the host system.

I'm willing to accept that there are two different issues at play in #171 and #181, but the fact that both of them deal with zombie processes forming within the container gives me hope that there may be a common solution to both issues.

**Comment by jest** [comment]
Anyone having problems with CTRL+C that *are not* solved by correcting ENTRYPOINT (as described in comment https://github.com/Microsoft/mssql-docker/issues/171#issuecomment-346133376), please test 2017-CU5. According to https://support.microsoft.com/en-us/help/4093805/fix-can-t-stop-sql-server-linux-docker-container-via-docker-stop it's solved there.

**Comment by keydon** [comment]
the changes described in https://github.com/Microsoft/mssql-docker/issues/171#issuecomment-346133376 *do* solve this issue.
But it seems Microsoft does not use this [Dockerfile](https://github.com/Microsoft/mssql-docker/blob/master/linux/mssql-server-linux/Dockerfile) for their actual images.

Doing this myself in my docker-compose file fixes the issue for me.
```
version: '3'
services:
  database:
    image: microsoft/mssql-server-linux:2017-latest
    environment:
      - MSSQL_SA_PASSWORD=xxx
      - ACCEPT_EULA=Y
    command: ["/opt/mssql/bin/sqlservr"]
```

**Comment by keydon** [comment]
ah sorry, nevermind. my image was too old.

**Comment by kichalla** [comment]
I am using CU12 and I am seeing the same issue

**Comment by badeball** [comment]
I've faced some issues with this as well. I have been using a version which does not spawn mssql inside a shell (IE. I've been using a sufficiently recent version that contains addd8374e7ff488a916e4ed1ec634b364b649209), but still experience inability to shut down the container. `docker kill` halts and I can't even restart the daemon, I can only restart the machine.

The logs indicate that a signal was received, but it apparently entered some weird state afterwards.

```
[...]
2019-06-18 09:05:39.68 spid6s      Always On: The availability replica manager is going offline because SQL Server is shutting down. This is an informational message only. No user action is required.
2019-06-18 09:05:39.68 spid6s      SQL Server is terminating in response to a 'stop' request from Service Control Manager. This is an informational message only. No user action is required.
2019-06-18 09:05:39.78 spid22s     Service Broker manager has shut down.
2019-06-18 09:05:43.43 Logon       Error: 18451, Severity: 14, State: 1.
2019-06-18 09:05:43.43 Logon       Login failed for user 'NT AUTHORITY\SYSTEM'. Only administrators may connect at this time. [CLIENT: 127.0.0.1]
2019-06-18 09:05:48.61 Logon       Error: 18451, Severity: 14, State: 1.
2019-06-18 09:05:48.61 Logon       Login failed for user 'NT AUTHORITY\SYSTEM'. Only administrators may connect at this time. [CLIENT: 127.0.0.1]
2019-06-18 09:10:53.49 Logon       Error: 18451, Severity: 14, State: 1.
2019-06-18 09:10:53.49 Logon       Login failed for user 'NT AUTHORITY\SYSTEM'. Only administrators may connect at this time. [CLIENT: 127.0.0.1]
```

While a normal shutdown looks like following.

```
[...]
2019-06-18 10:33:05.68 spid6s      Always On: The availability replica manager is going offline because SQL Server is shutting down. This is an informational message only. No user action is required.
2019-06-18 10:33:05.68 spid6s      SQL Server is terminating in response to a 'stop' request from Service Control Manager. This is an informational message only. No user action is required.
2019-06-18 10:33:06.11 spid23s     Service Broker manager has shut down.
2019-06-18 10:33:11.29 spid6s      SQL Trace was stopped due to server shutdown. Trace ID = '1'. This is an informational message only; no user action is required.
```

**Comment by Danielku15** [comment]
Using `mcr.microsoft.com/mssql/server:2022-latest` and I seem to face the same issue. SQL Server gets stuck on stopping the container. When I wait long enough (sometimes minutes) I get some timeout errors on the stop and then all of a sudden the container is also stopped.

**Comment by mabrarov** [comment]
I use mcr.microsoft.com/mssql/server:2022-latest docker image and I face the same issue. 

I believe that the root cause of this issue is located in the shell script used as container ENTRYPOINT - in /opt/mssql/bin/launch_sqlservr.sh:

```bash
...

"$@" &
pid="$!"

/opt/mssql/bin/run_custom_setup.sh
if [ $? -ne 0 ]; then
    exit 1
fi

wait $pid
```

The lack of signal trap(s) forwarding signals to `pid` (to the SQL Server instance process) in this script makes the script terminated by Docker without:

1. Sending (stop) signal to SQL Server process (to `pid`), i.e. shutdown notification of SQL Server.
1. Waiting for completion of shutdown of SQL Server process.

I used shell script from WildFly as example:

https://github.com/wildfly/wildfly-core/blob/dbe2c0a26f28ea0c11da1825719c7970621cfec3/core-feature-pack/common/src/main/resources/content/bin/standalone.sh#L362

and modified /opt/mssql/bin/launch_sqlservr.sh (which I bind to container to replace original script) this way (I tried to follow [Google Shell Style Guide](https://google.github.io/styleguide/shellguide.html)):

```diff
@@ -20,9 +20,40 @@ fi
 "$@" &
 pid="$!"
 
+# shellcheck disable=SC2064
+trap "kill -HUP  $(printf '%q' "${pid}")" HUP
+# shellcheck disable=SC2064
+trap "kill -TERM $(printf '%q' "${pid}")" INT
+# shellcheck disable=SC2064
+trap "kill -QUIT $(printf '%q' "${pid}")" QUIT
+# shellcheck disable=SC2064
+trap "kill -PIPE $(printf '%q' "${pid}")" PIPE
+# shellcheck disable=SC2064
+trap "kill -TERM $(printf '%q' "${pid}")" TERM
+
 /opt/mssql/bin/run_custom_setup.sh
 if [ $? -ne 0 ]; then
     exit 1
 fi
 
 wait $pid
+wait_status=$?
+
+if [ "${wait_status}" -gt 128 ]; then
+    signal=$(("${wait_status}" - 128))
+    signal_name="$(kill -l "${signal}")"
+    echo "*** SQL Server process (${pid}) received ${signal_name} signal ***" >&2
+fi
+
+if [ "${wait_status}" -lt 127 ]; then
+    mssql_status="${wait_status}"
+else
+    mssql_status=0
+fi
+
+# Wait for $pid to stop.
+while kill -0 "${pid}" >/dev/null 2>&1; do
+    wait "${pid}" 2>/dev/null
+done
+
+exit "${mssql_status}"
```

This fix works for me:

```
$ docker compose up sqlserver
...
2026-02-19 23:04:06.26 spid28s     Recovery is complete. This is an informational message only. No user action is required.
2026-02-19 23:04:06.28 spid36s     The default language (LCID 0) has been set for engine and full-text services.
2026-02-19 23:04:06.43 spid36s     The tempdb database has 8 data file(s).
```

then in another terminal

```
$ docker compose stop -t 600 sqlserver
[+] stop 1/1
 ✔ Container eventprocessor-sqlserver-1 Stopped                                                                                                                                                         0.4s
$ echo $?
0
$ docker compose ps -a sqlserver
NAME                         IMAGE                                        COMMAND                  SERVICE     CREATED              STATUS                      PORTS
eventprocessor-sqlserver-1   mcr.microsoft.com/mssql/server:2022-latest   "/opt/mssql/bin/laun…"   sqlserver   About a minute ago   Exited (0) 16 seconds ago   
```

and in original terminal I get:

```
sqlserver-1  | *** SQL Server process (8) received TERM signal ***
2026-02-19 23:05:10.58 spid28s     Always On: The availability replica manager is going offline because SQL Server is shutting down. This is an informational message only. No user action is required.
2026-02-19 23:05:10.58 spid28s     SQL Server is terminating in response to a 'stop' request from Service Control Manager. This is an informational message only. No user action is required.
2026-02-19 23:05:10.58 spid28s     .NET Framework runtime has been stopped.
RecoveryUnit::Shutdown. IsOnline: 0RecoveryUnit::Shutdown. IsOnline: 0RecoveryUnit::Shutdown. IsOnline: 0RecoveryUnit::Shutdown. IsOnline: 02026-02-19 23:05:10.65 spid28s     SQL Trace was stopped due to server shutdown. Trace ID = '1'. This is an informational message only; no user action is required.
sqlserver-1  | 
sqlserver-1 exited with code 0
```

**Comment by tracker1** [comment]
@twright-msft on prioritizing startup vs shutdown... my own $.02 is that I would prefer to see both actions take under 10 seconds under typical conditions...  As for what is "typical" is hard to say as hardware varies a lot.

But maybe target a Linux VM of a modern laptop CPU with 4 cores and 8gb ram assigned to sat Ubuntu Server (no gui) and a PCIE Gen 4 nvme drive.  I know drive speed and CPU speeds can vary a bit... but it's still probably representative of what developers are actually using, where servers are likely to have more resources than less.

Another thing that would be nice, would be some means of improving the READY detection of SQL Server inside a container...  A /tmp/sql-up file that is created after startup, or a heartbeat http endpoint.  Other RDBMS seem to handle this much better, though they will come with other caveats.

**Comment by jest** [comment]
8 years later still this is not fixed... Wow...

**Comment by tobias-graf-p** [comment]
I am experiencing the same issue. Looking forward to the analysis results in #968 (and hopefully a fix).
