### ISSUE TITLE
filestream supporting in sql server 2019 on linux

### ISSUE THREAD

**Issue by nikkhoo63** [microsoft/mssql-docker#480]
Hi
I want to restore a backup of database with filestream into sql server 2019 preview in ubuntu.
but when I restore the database this error received:
The path '/var/opt/mssql/data/dbname_FileStream' cannot be used for FILESTREAM files. For information about supported paths, see SQL Server Books Online.
according to [this](https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-release-notes?view=sql-server-2017#Unsupported) I know this feature on linux not supported in mssql 2017  but there is no mention of this feature in sql server 2019 preview. 
I want to know sql server 2019 will support this feature on linux?
if not supported is another solution to solve this problem?
thanks

**Comment by amitmsft** [comment]
We do not have support for filestream for SQL Server 2019. Please file a feedback item [here](https://feedback.azure.com/forums/908035-sql-server) for this feature. If you are looking to store files and access them using SQL Server Linux containers, then you could evaluate HDFS storage capabilities with [SQL Server 2019 Big Data Clusters](https://docs.microsoft.com/en-us/sql/big-data-cluster/big-data-cluster-overview?view=sqlallproducts-allversions
).

**Comment by jducobu** [comment]
@amitmsft, do you mean FILESTREAM is now replaced by SQL Server 2019 Big Data Clusters?

**Comment by amitmsft** [comment]
Filestream is not replaced with Big Data Cluster. Big Data Cluster lets you fulfil the same scenario and is going to be available in SQL Server 2019 RTM, hence the ask to evaluate Big Data Cluster if you need similar capability with SQL Server on Linux.

**Comment by JohnGalt1717** [comment]
This is a major blocker for a lot of companies with filestreams. Really need to be able to get this working in SQL Server for linux and docker.

**Comment by unicorn667** [comment]
any news? i can´t find nothing about this topic in what´s new document

https://docs.microsoft.com/en-us/sql/sql-server/what-s-new-in-sql-server-ver15?view=sql-server-ver15

**Comment by tedivm** [comment]
Well this is annoying- having support for this would definitely help our developers.

**Comment by srNext** [comment]
We evaluated running SQL Server 2019 on Linux (and containers, particularly for the dev environment) as we are about to upgrade from 2017, since all our other servers are already on Linux anyway.
Only to find out that filestream/filetable are not supported on Linux....
This is a major blocker for us and as such we will have to stick with a single Windows machine once again for the database, just because of this one thing. I agree with @JohnGalt1717 that you really need to get this working on Linux and Docker. Been over a year since and no change on this matter.

**Comment by RichardHubertPtw** [comment]
A quick status on this would be appreciated. We cannot expect our customers (standard IT-centers worldwide) to install a BigDataCluster just to support one application. As such, the suggestion above is not feasible for most.

**Comment by ArthurBorsboom** [comment]
A gentle ping on the status of filestream for MSSQL for linux.

**Comment by bNobo** [comment]
If you really need this feature you can vote for it here : https://feedback.azure.com/forums/908035-sql-server/suggestions/38269312-filestream-and-filetable-for-sql-server-2019-linux

**Comment by srNext** [comment]
As additional information for anybody interested in this topic:
Apart from the feedback page that bNobo linked, there's also an older issue about this to be found here: https://github.com/microsoft/mssql-docker/issues/47

We recently re-evaluated Linux again, as we are really not particularly keen to keep this one Windows VM running just for the database, however there seems to be no change on the topic at all nor does it seem like we can expect any progress on this in the near future. This topic as been in the room for years and no updates by Microsoft at all.
On the other hand we would really like to stick with SQL Server, as it always ran without issues, plus we use other products like .Net Core from Microsoft anyway (it is about pro Linux, not contra Microsoft).
As far as it goes for our company, we are now considering alternative options like creating some custom document store system, just to get rid of the issue already.
Sorry that I have no better news for anybody reading this but you will have to come up with your own solution apparently.

**Comment by sintetico82** [comment]
Is there some news about this? 😊

**Comment by bota87** [comment]
The link provided by @bNobo didn't work for me, I've found this instead
https://feedback.azure.com/d365community/idea/4086746d-5925-ec11-b6e6-000d3a4f0da0
https://feedback.azure.com/d365community/idea/74ef2b5e-5125-ec11-b6e6-000d3a4f0da0

**Comment by Bertramp** [comment]
Come on Microsoft.. it has been 14 years since Filestream was introduced. Move your butts so we can make a proper docker image for SQL server

**Comment by ZengZhenfei** [comment]
please fix it

**Comment by thenktor** [comment]
Please add FILESTREAM support

**Comment by thesqlsith** [comment]
We would like to thank everyone for the continued discussion around this topic.

The original issue in this thread was our inability to support a restore of a database backup that contained filestream data on SQL Server on Linux. That particular issue had been fixed after the preview version of SQL Server 2019 was released. SQL Server on Linux does not have the ability currently to support access to the filestream/filetable feature after that action however. There was a duplicate issue opened (https://github.com/microsoft/mssql-docker/issues/188) regarding filestream support where we have encouraged that this issue be upvoted on an existing Ideas system item along with any details that can be provided regarding the workload and scenario where filestream support is required.

**Comment by khalilsheikh** [comment]
is the FileStream feature for Linux is coming or its not?

**Comment by thesqlsith** [comment]
Thanks @khalilsheikh for inquiring about this GitHub issue. The original issue in this thread was related to the inability of SQL Server on Linux to support restoring databases that contained filestream/filetable data structures. That problem had been fixed in the general release of SQL Server 2019 and later.

For the question regarding if the filestream feature will be coming to Linux, please see https://github.com/microsoft/mssql-docker/issues/188. There is no short answer that I can provide at this time to that question, but I will repost part of what was shared on GitHub issue 188 here, however.

For FILESTREAM support on Linux containers, as of the time of this message, that scenario is still not supported. We would encourage you to upvote the Ideas feedback item (https://feedback.azure.com/d365community/idea/4086746d-5925-ec11-b6e6-000d3a4f0da0) along with providing any additional details that you can regarding the workload and/or scenario which would require FILESTREAM/FILETABLE support from within a SQL Server on Linux container.

"Why do Linux containers not have support for FILESTREAM?" Great question. The TLDR answer is upvotes on the Ideas platform (formerly known as UserVoice) helps with driving the prioritization of blocking issues such as the one that this GitHub issue thread is based upon. The slightly longer answer (as of the date of this post) would be twofold.

Since the FILESTREAM feature is based on the WinFS (https://en.wikipedia.org/wiki/WinFS) code, it has tight integration with the NTFS and ReFS filesystems. This integration comes in the form of a Windows kernel filter driver, RsFX - https://learn.microsoft.com/sql/relational-databases/blob/filestream-sql-server). The current NTFS filesystem support in Linux does not support all of the semantics required by this driver (i.e. NTFS-3g https://github.com/tuxera/ntfs-3g#readme). We are investigating how filesystems like xfs could be leveraged but that works is still ongoing. 

SQL Server on Linux is built on a hybrid technology that we refer to as SQLPAL (SQL Platform Abstraction Layer - https://cloudblogs.microsoft.com/sqlserver/2016/12/16/sql-server-on-linux-how-introduction/) as opposed to a direct port of SQL Server that executes natively on Linux. This essentially means that in addition to any Linux native filesystem changes, SQLPAL itself requires additional work as it is a user space construct with no kernel space component (https://learn.microsoft.com/en-us/archive/blogs/bobsql/sql-server-on-linux-elf-and-pe-images-just-work).

We do not have any timelines that we can share at this point in time, but still strongly encourage that you upvote the Ideas platform item and provide additional detailed feedback.

**Comment by asp55** [comment]
> Thanks @khalilsheikh for inquiring about this GitHub issue. The original issue in this thread was related to the inability of SQL Server on Linux to support restoring databases that contained filestream/filetable data structures. That problem had been fixed in the general release of SQL Server 2019 and later.

@thesqlsith I'm on `Microsoft SQL Server 2019 (RTM-CU25) (KB5033688) - 15.0.4355.3 (X64)` but am still getting the same error @nikkhoo63 described when I try to restore a database that contains a filestream `The path '/var/opt/mssql/data/DOCUMENTS_13A98F69.mdf' cannot be used for FILESTREAM files. For information about supported paths, see SQL Server Books Online.`

Is there something I need to include in the restore command to utilize the fix you mentioned?
