### ISSUE TITLE
SQL Server respecting Kubernetes limits?

### ISSUE THREAD

**Issue by justindavies** [microsoft/mssql-docker#814]
Hi team, we've had an interesting issue in the AKS repo from a customer:

https://github.com/Azure/AKS/issues/3457

Can you let me know if there is anything needed on your side for SQL server to respect limits on the pod ?

**Comment by mdebruijnbefrank** [comment]
Any news on this issue? We are facing OOMTerminated problems since upgrading our AKS cluster with SQL Server.

**Comment by amitkh-msft** [comment]
Yes, this is an issue that we see because SQL Server currently does not work with cgroup v2. we are working on this and I dont have a timeline on when this will be fixed but this is work in progress. We will keep you updated.

**Comment by martijndebruijn** [comment]
Any updates on this issue?

**Comment by adoprog** [comment]
@amitkh-msft Is the work still in progress? Will it be fixed at all?
SQL Server is simply unusable in latest Kubernetes because of this.

**Comment by amitkh-msft** [comment]
yes, we will prioritize this over other items in the backlog. I may soon have an update on the timeline

**Comment by rmannibucau** [comment]
Any news?

**Comment by LeeRoyManea** [comment]
i have also tried to limit the memory in the sql server settings

`sp_configure 'show advanced options', 1;
GO
RECONFIGURE;
GO
sp_configure 'max server memory', 1024;
GO
RECONFIGURE;
GO

SELECT [name], [value], [value_in_use]
FROM sys.configurations
WHERE [name] = 'max server memory (MB)' OR [name] = 'min server memory (MB)';
`

also with the Environment Variable that is discribed in the documentation 

`MSSQL_MEMORY_LIMIT_MB: "1024"`

but nothing is working. 

Only a very small website is runnig on my sql server instance. 

Before i tried to limit the ram it was at 8gb.  Now its on 4gb but growing. 

Is there any workarround?  Or do i have to host a vm exspeccialy only for the sql server?

**Comment by vcipriani** [comment]
We are still seeing this issue.   @amitkh-msft - any updates?

**Comment by julia-yin** [comment]
Hi @amitkh-msft, has this issue been solved yet?

**Comment by LeeRoyManea** [comment]
@vcipriani @julia-yin  i cant tell what the real current state is. 

My Experience of the past months.  The Container crashed out of nowhere. Now running in OOM when the set limits are overflown.  And now is the ram ussage about 2gigs.  But in return i have the feeling the performance is worse

**Comment by amitkh-msft** [comment]
The support for Cgroup v2 is now in for SQL Server 2025 preview bits and SQL Server 2022 CU 20
