### ISSUE TITLE
Unable to start container on Linux 6.7

### ISSUE THREAD

**Issue by quinnjr** [Microsoft/mssql-docker#868]
Currently unable to start the container on Arch Linux as the host OS. The dump files for the failing sqlservr process don't really provide any insight as to why:

```
docker compose logs db
db-1  | SQL Server 2022 will run as non-root by default.
db-1  | This container is running as user mssql.
db-1  | Your master database file is owned by mssql.
db-1  | To learn more visit https://go.microsoft.com/fwlink/?linkid=2099216.
db-1  | This program has encountered a fatal error and cannot continue running at Mon Jan 15 18:19:00 2024
db-1  | The following diagnostic information is available:
db-1  | 
db-1  |          Reason: 0x00000001
db-1  |          Signal: SIGABRT - Aborted (6)
db-1  |           Stack:
db-1  |                  IP               Function
db-1  |                  ---------------- --------------------------------------
db-1  |                  000064eb280a3ce1 std::__1::bad_function_call::~bad_function_call()+0x96661
db-1  |                  000064eb280a36a6 std::__1::bad_function_call::~bad_function_call()+0x96026
db-1  |                  000064eb280a2c2f std::__1::bad_function_call::~bad_function_call()+0x955af
db-1  |                  00007c18f8810520 __sigaction+0x50
db-1  |                  00007c18f88649fc pthread_kill+0x12c
db-1  |                  00007c18f8810476 raise+0x16
db-1  |                  00007c18f87f67f3 abort+0xd3
db-1  |                  000064eb28074d96 std::__1::bad_function_call::~bad_function_call()+0x67716
db-1  |                  000064eb280b15b4 std::__1::bad_function_call::~bad_function_call()+0xa3f34
db-1  |                  000064eb280df318 std::__1::bad_function_call::~bad_function_call()+0xd1c98
db-1  |                  000064eb280df0fa std::__1::bad_function_call::~bad_function_call()+0xd1a7a
db-1  |                  000064eb2807b20a std::__1::bad_function_call::~bad_function_call()+0x6db8a
db-1  |                  000064eb2807ae80 std::__1::bad_function_call::~bad_function_call()+0x6d800
db-1  |         Process: 10 - sqlservr
db-1  |          Thread: 157 (application thread 0x264)
db-1  |     Instance Id: 83ef72ce-1100-44c4-913c-45d0df61ae44
db-1  |        Crash Id: 05e56c63-9bd1-47db-b3d5-c1f58cebd578
db-1  |     Build stamp: a9299dd605c652a3cea4246273441bcfaf48afb4b482ab9dc43771eecaf6600b
db-1  |    Distribution: Ubuntu 22.04.3 LTS
db-1  |      Processors: 32
db-1  |    Total Memory: 67119079424 bytes
db-1  |       Timestamp: Mon Jan 15 18:19:00 2024
db-1  |      Last errno: 2
db-1  | Last errno text: No such file or directory
db-1  | Capturing a dump of 10
db-1  | Successfully captured dump: /var/opt/mssql/log/core.sqlservr.1_15_2024_18_19_0.10
db-1  | Executing: /opt/mssql/bin/handle-crash.sh with parameters
db-1  |      handle-crash.sh
db-1  |      /opt/mssql/bin/sqlservr
db-1  |      10
db-1  |      /opt/mssql/bin
db-1  |      /var/opt/mssql/log/
db-1  |      
db-1  |      83ef72ce-1100-44c4-913c-45d0df61ae44
db-1  |      05e56c63-9bd1-47db-b3d5-c1f58cebd578
db-1  |      
db-1  |      /var/opt/mssql/log/core.sqlservr.1_15_2024_18_19_0.10
db-1  | 
db-1  | Ubuntu 22.04.3 LTS
db-1  | Capturing core dump and information to /var/opt/mssql/log...
```

Docker-compose file:

```
version: '3'
services:
  db:
    image: 'mcr.microsoft.com/mssql/server:2022-latest'
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=<there would be a password here>
      - MSSQL_PID=Developer
    volumes:
      - ./logs:/var/opt/mssql/log
      - ./data:/var/opt/mssql/data
    ports:
      - 1433:1433
```

Docker logs and data directory are set as UID:GID 10001:10001.

**Comment by erikbozic** [comment]
I have the same issue. Found that it's the 6.7 kernel update. (https://github.com/microsoft/mssql-docker/issues/858#issuecomment-1892216070)

Rolling back to 6.6.10 makes it work again.

**Comment by thomasvm** [comment]
I expericenced the same behavior today. First my existing container grew in size very quickly. I tried creating other containers but they all failed with the above message. 

It took me a while to figure out that downgrading my kernel fixes the issue, but downgrading to 6.6.11 did the trick.

**Comment by unlogicalcode** [comment]
I can also confirm, I have the same behaviour. 
It works with Kernel 6.6 and with 6.7 I get a similiar Message as above.

**Comment by quinnjr** [comment]
I downgraded my kernel and the container now functions.

Is this limited to just this container or docker needing to update something to be compatible with the 6.7 kernel?

**Comment by huestack** [comment]
I have same problem running container in Podman, but the Docker container is running without any problem. I simply pulled the image `sudo podman pull mcr.microsoft.com/mssql/server:2022-latest`, and ran it:
```
sudo podman run -e "ACCEPT_EULA=Y" -e "MSSQL_SA_PASSWORD=Str0ngPass!" -p 1433:1433 --name sql-test --hostname sql-test -d  mcr.microsoft.com/mssql/server:2022-latest
```
Attached is a log file.
[sql-test.log](https://github.com/microsoft/mssql-docker/files/13961652/sql-test.log)

**Comment by LJFloor** [comment]
Can confirm on Arch Linux, both the docker images for versions 2017, 2019 and 2022 and the [AUR version](https://aur.archlinux.org/packages/mssql-server) give the same result.

```
Last errno text: No such file or directory
```

After [downgrading the kernel](https://wiki.archlinux.org/title/downgrading_packages#Downgrading_the_kernel) to version `6.6.10-arch1-1` it starts successfully.

**Comment by CodeKJ** [comment]
I can confirm this on Nobara 39 with 6.7.0 kernel. Exactly same issue for 2017, 2019, 2022 mssql.
6.6.9 works fine.

**Comment by erikbozic** [comment]
It seems like this was solved in the aur repo package `mssql-server`: https://aur.archlinux.org/packages/mssql-server#comment-953063.
However I'm still having trouble building the needed dependency to verify...

**Comment by kshpytsya** [comment]
For what it is worth:

running Gentoo with custom 6.7.x kernel.
It looks like it fails trying to access cgroup v1 "/sys/fs/cgroup/memory/memory.limit_in_bytes".
I suspect that switching to cgroup to "hybrid" would fix the issue but I am not up to rebooting my machine now.

```sh
$ docker run -it --rm -e ACCEPT_EULA=Y -e MSSQL_PID=Developer mcr.microsoft.com/mssql/server:2022-latest -- /bin/bash
sleep 1000
```

in another terminal, run

```sh
ps fax|less
# find pid of bash which is parent of sleep
sudo strace -o mssql.strace -f -s1000 -p <bash-in-mssql-docker>
```

return to the first terminal, `Ctrl-C` the sleep and run `/opt/mssql/bin/sqlservr`. Run `/opt/mssql/bin/sqlservr` and wait for it to crash. Go to the seconf terminal, interrupt strace. 

```sh
$ grep -P '"/(proc|sys).*ENOENT' mssql.strace
9999 openat(AT_FDCWD, "/sys/fs/cgroup/memory/memory.limit_in_bytes", O_RDONLY) = -1 ENOENT (No such file or directory)
```

**Comment by ibauersachs** [comment]
I think the `ENOENT` is not the issue, especially not `/sys/fs/cgroup/memory/memory.limit_in_bytes` since this doesn't exist on Kernel 6.6.13 either, and mssql runs fine there.
My crashlogs on 6.7.1 showed Invalid argument / 22 / EINVAL:

```
This program has encountered a fatal error and cannot continue running at Mon Jan 22 18:09:17 2024
The following diagnostic information is available:

         Reason: 0x00000001
         Signal: SIGABRT - Aborted (6)
          Stack:
                 IP               Function
                 ---------------- --------------------------------------
                 0000613cdff2ace1 std::__1::bad_function_call::~bad_function_call()+0x96661
                 0000613cdff2a6a6 std::__1::bad_function_call::~bad_function_call()+0x96026
                 0000613cdff29c2f std::__1::bad_function_call::~bad_function_call()+0x955af
                 0000753f7ee4d520 __sigaction+0x50
                 0000753f7eea19fc pthread_kill+0x12c
                 0000753f7ee4d476 raise+0x16
                 0000753f7ee337f3 abort+0xd3
                 0000613cdfefbd96 std::__1::bad_function_call::~bad_function_call()+0x67716
        Process: 10 - sqlservr
         Thread: 161 (application thread 0x278)
    Instance Id: ba778b4b-ea20-4f3c-98fa-2002d4c8e68c
       Crash Id: 3674de73-5de7-494e-8530-2520421dd97f
    Build stamp: a9299dd605c652a3cea4246273441bcfaf48afb4b482ab9dc43771eecaf6600b
   Distribution: Ubuntu 22.04.3 LTS
     Processors: 16
   Total Memory: 29180137472 bytes
      Timestamp: Mon Jan 22 18:09:17 2024
     Last errno: 22
Last errno text: Invalid argument
```

**Comment by CryptoSiD** [comment]
The problem is still there with kernel 6.7.2

**Comment by Green0wl** [comment]
same problem on `6.7.1-arch1-1`

**Comment by GieltjE** [comment]
As a bad side effect the lsof process it spawns starts eating a core

**Comment by fbrosseau** [comment]
Hello,

The issue has been identified and should be fixed in the next SQL Server 2022 CU, but we cannot commit to a specific CU release or timeline as sometimes plans can unexpectedly change. No further investigation or data points should be needed for this.

It is unrelated to cgroups, and at first glance it might be a kernel bug (but do not quote me on this) - it appears that as of 6.7, `mmap` without `MAP_FIXED` may ignore the `address` hint even if the hinted region is in fact available. I have not investigated the kernel side of things further, but I think it might be related to [this series of changes](https://lore.kernel.org/linux-mm/tencent_1A8C66C86EE30ADF9160AC36B46314AE5306@qq.com/T/) and/or its preceeding/succeeding changes.

Knowing this, I cannot think of any workaround other than sticking to 6.6 in the meantime.

**Comment by vermarine** [comment]
> Hello,
> 
> The issue has been identified and should be fixed in the next SQL Server 2022 CU, but we cannot commit to a specific CU release or timeline as sometimes plans can unexpectedly change. No further investigation or data points should be needed for this, but thank you all for reporting and for looking for potential causes.
> 
> It is unrelated to cgroups, and at first glance it might be a kernel bug (but do not quote me on this) - it appears that as of 6.7, `mmap` without `MAP_FIXED` may sometimes ignore the `address` hint even if the hinted region is in fact available. I have not investigated the kernel side of things further, but I think it might be related to [this series of changes](https://lore.kernel.org/linux-mm/tencent_1A8C66C86EE30ADF9160AC36B46314AE5306@qq.com/T/) and/or its preceding/following changes.
> 
> Knowing this, I cannot think of any workaround other than sticking to 6.6 in the meantime.

Thank you very much for the patch. Are there plans to also backport it to 2019?

**Comment by jaddie** [comment]
Just wanted to write to say I am so glad you have all written on here, I didn't even think about the fact I just upgraded my arch system, I was about to start tearing things apart this has saved me a heck of a lot of time, whilst I am here to say thank you, I can also confirm this is still happening on Arch Linux on 6.7.4

**Comment by massouji82** [comment]
Hi! We are running a msql based prosject on a mac and use the image `mcr.microsoft.com/mssql/server:2019-latest` through Podman. Podman will not start a container with this image since the kernel was updated. How kan we revert the kernel version of the host or is there another workaround? Any help would be highly appreciated. Thanks!

**Comment by johnvanham** [comment]
Same issue with Fedora 39 on 6.7.2 and 6.7.3, but fine on 6.6.x and 6.5.x

**Comment by zzzeek** [comment]
I think MSFT should strongly consider backporting this at least to SQL Server 2019 if not even 2017 as well.   As people continue to upgrade their kernels this is going to be happening on an ever larger scale to existing SQL Server linux / container installations.

**Comment by kshpytsya** [comment]
> Thank you very much for the patch. Are there plans to also backport it to 2019?
Am I missing something? I do not see any updated Docker images for `mcr.microsoft.com/mssql/server:2022-latest` that would make it run on `6.7.*`.

**Comment by markbeazley** [comment]
> > Thank you very much for the patch. Are there plans to also backport it to 2019?
> > Am I missing something? I do not see any updated Docker images for `mcr.microsoft.com/mssql/server:2022-latest` that would make it run on `6.7.*`.

It should be included in the next CU, no date estimate

> The issue has been identified and should be fixed in the next SQL Server 2022 CU, but we cannot commit to a specific CU release or timeline as sometimes plans can unexpectedly change. No further investigation or data points should be needed for this, but thank you all for reporting and for looking for potential causes.


I've been keeping an eye on [this page](https://learn.microsoft.com/en-us/troubleshoot/sql/releases/sqlserver-2022/build-versions) for a presumably CU12 to be released.

**Comment by asergios** [comment]
Not working on `6.7.5` either.

**Comment by brunofin** [comment]
I am glad I ran into this issue. This started happening recently on Fedora 39. Kernel 6.7.4. I will test another kernel and report back.

**Comment by daef** [comment]
mysql, pgsql and sqlite all work no problem. but m$ seems to be able to afford not to give a crap about a regression in the latest kernel. not amused.

**Comment by Run-c0de** [comment]
─ docker logs 9536fdc556e1                                                                                                                                                                                                          ─╯
This program has encountered a fatal error and cannot continue running at Tue Feb 27 19:29:45 2024
The following diagnostic information is available:

         Reason: 0x00000001
         Signal: SIGABRT - Aborted (6)
          Stack:
                 IP               Function
                 ---------------- --------------------------------------
                 000056dc072752fc <unknown>
                 000056dc07274d42 <unknown>
                 000056dc07274351 <unknown>
                 00007c8fbb447090 killpg+0x40
                 00007c8fbb44700b gsignal+0xcb
                 00007c8fbb426859 abort+0x12b
                 000056dc071fb3d2 <unknown>
                 000056dc07287304 <unknown>
                 000056dc072bc388 <unknown>
                 000056dc072bc16a <unknown>
                 000056dc0720724a <unknown>
                 000056dc07206e9f <unknown>
        Process: 12 - sqlservr
         Thread: 83 (application thread 0x134)
    Instance Id: 252d75bf-d3a4-4b38-a78f-b83488b53759
       Crash Id: 855b8579-9053-4856-ad38-69e4a54d6ff6
    Build stamp: e149a9e980d9936d4f4a616b06112de0e7b2f4e45c2cd3a0884ae319ad3d13b7
   Distribution: Ubuntu 20.04.6 LTS
     Processors: 12
   Total Memory: 16618233856 bytes
      Timestamp: Tue Feb 27 19:29:45 2024
     Last errno: 2
Last errno text: No such file or directory
Capturing a dump of 12
Successfully captured dump: /var/opt/mssql/log/core.sqlservr.2_27_2024_19_29_45.12
Executing: /opt/mssql/bin/handle-crash.sh with parameters
     handle-crash.sh
     /opt/mssql/bin/sqlservr
     12
     /opt/mssql/bin
     /var/opt/mssql/log/
     
     252d75bf-d3a4-4b38-a78f-b83488b53759
     855b8579-9053-4856-ad38-69e4a54d6ff6
     
     /var/opt/mssql/log/core.sqlservr.2_27_2024_19_29_45.12

Ubuntu 20.04.6 LTS
Capturing core dump and information to /var/opt/mssql/log...
/bin/cat: /proc/12/maps: Permission denied
SQL server is unavailable - sleeping

**Comment by MPavleski** [comment]
Any plans to upgrade the Docker image to resolve this issue?

**Comment by thomasvm** [comment]
Well, first there needs to be a new CU release, the last one is from january 2024 and there seems to be a pace of about 1 release per month, so a new release is about to be expected. But the team is not communicating release dates, so we can only wait at this point in time. 

Keep track of [this page](https://learn.microsoft.com/en-us/troubleshoot/sql/releases/sqlserver-2022/build-versions) to see whether a new CU is released.

**Comment by brunofin** [comment]
It's a bit infuriating that we need to wait for a critical bug fix to land on a monthly cumulative update without being even certain whether it actually will.

It would be much more productive instead to post here instructions on how to migrate the database to postgres and be done with it lol

**Comment by irrefl** [comment]
Microsoft Needs You Use their Garbage Images that's why they remove Linux based images

**Comment by CryptoSiD** [comment]
When can we hope for CU12 that will include the fix?

It's been 2 weeks already.

**Comment by YusufMavzer** [comment]
Tested it too and can confirm kernel 6.7+ doesn't work. When will it be fixed?

 @erikbozic

**Comment by GieltjE** [comment]
> When can we hope for CU12 that will include the fix?
> 
> It's been 2 weeks already.

See the release site, usualy releases in the second week of the month

**Comment by YusufMavzer** [comment]
> When can we hope for CU12 that will include the fix?
> 
> It's been 2 weeks already.

Here you can see when the latest release was
https://hub.docker.com/_/microsoft-mssql-server

**Comment by rg4github** [comment]
> > When can we hope for CU12 that will include the fix?
> > It's been 2 weeks already.
> 
> Here you can see when the latest release was https://hub.docker.com/_/microsoft-mssql-server

Maybe I shouldn’t be viewing this on my phone, but are there release dates on this page?

**Comment by alex1712** [comment]
Yes, if you scroll down you see a table with the list of tags with the latest update date, thats how I understand it at least

**Comment by rg4github** [comment]
> Yes, if you scroll down you see a table with the list of tags with the latest update date, thats how I understand it at least

Thanks for clarifying! I opened the page on my desktop and the dates were clearly visible there. Now that I know where to look I can see the dates on my phone as well; I just have to scroll sideways on the unmarked table :-p  (It’s like playing Myst,
where you have to look behind doors…)

**Comment by brunofin** [comment]
Now Fedora has updated its kernel to 6.7.7 which unsurprisingly still doesn't work.

The problem now, is that now there are 3 `6.7.x` kernels installed meaning the `6.6.x` backup kernel was effectively uninstalled automatically. So now whoever still needs to use this will need to learn how to manually install a kernel version which I am sure it's not gonna be fun.

Thanks Microsoft.

**Comment by brunofin** [comment]
For anyone looking to install kernel 6.6 on Fedora:

https://fedoramagazine.org/install-kernel-koji/

Here's the link for the kernel for F39: https://koji.fedoraproject.org/koji/buildinfo?buildID=2386947

Download `kernel-6.6.14-200.fc39.x86_64.rpm`, `kernel-core-6.6.14-200.fc39.x86_64.rpm` and `kernel-modules-6.6.14-200.fc39.x86_64.rpm`, then use dnf to install them as the guide describes.

**Comment by irrefl** [comment]
Thanks@brunofin

**Comment by markbeazley** [comment]
> Now Fedora has updated its kernel to 6.7.7 which unsurprisingly still doesn't work.
> 
> The problem now, is that now there are 3 `6.7.x` kernels installed meaning the `6.6.x` backup kernel was effectively uninstalled automatically. So now whoever still needs to use this will need to learn how to manually install a kernel version which I am sure it's not gonna be fun.
> 
> Thanks Microsoft.

The best fix I've found for this on Fedroa (not sure what the steps are on other distros):

1. Have kernel 6.6 installed (not sure how to do this if its already been removed I did the following before that happened on my machine)
2. Get the list of bootable kernel paths `sudo grubby --info=ALL | grep ^kernel`:
```kernel="/boot/vmlinuz-6.7.7-200.fc39.x86_64"
kernel="/boot/vmlinuz-6.7.6-200.fc39.x86_64"
kernel="/boot/vmlinuz-6.7.5-200.fc39.x86_64"
kernel="/boot/vmlinuz-6.7.4-200.fc39.x86_64"
kernel="/boot/vmlinuz-6.6.14-200.fc39.x86_64"
kernel="/boot/vmlinuz-0-rescue-b7048036f6894f74977406c4d08c3213"
```
3. Set your default Kernel to 6.6 in grub using the path returned in the previous command in my case that would be: `sudo grubby --set-default=/boot/vmlinuz-6.6.14-200.fc39.x86_64` 
4. Reboot and check you are running Kernel 6.6 `uname -a`
5. As root edit `/etc/sysconfig/kernel` and change `UPDATEDEFAULT=yes` to `UPDATEDEFAULT=no`

What this will do is make sure your default boot kernel is 6.6, then the last change stops any kernel updates from changing your default boot kernel, and because the update won't remove the currently running kernel as long as you are booted into a 6.6 kernel when the update runs it wont be removed.

This is unfortuantly the kind of issue you are likely to run into when you are running a distro that tries to use the latest versions, the 6.6 kernel is a LTS release, 6.7 was only released in January.

Its for production workloads but they do list supported configurations, for running SQL Server in a docker container, [here](https://learn.microsoft.com/en-US/troubleshoot/sql/general/support-policy-sql-server#guidelines) and [here](https://learn.microsoft.com/en-us/sql/linux/sql-server-linux-setup?view=sql-server-ver16#supportedplatforms) on that list  RHEL 9 and SUSE are still on the 5.14 kernel and Ubuntu 22.04 is on 6.5.

**Comment by johnvanham** [comment]
> > Now Fedora has updated its kernel to 6.7.7 which unsurprisingly still doesn't work.
> > 
> > The problem now, is that now there are 3 `6.7.x` kernels installed meaning the `6.6.x` backup kernel was effectively uninstalled automatically. So now whoever still needs to use this will need to learn how to manually install a kernel version which I am sure it's not gonna be fun.
> > 
> > Thanks Microsoft.
> 
> The best fix I've found for this on Fedroa (not sure what the steps are on other distros):
> 
> 1. Have kernel 6.6 installed (not sure how to do this if its already been removed I did the following before that happened on my machine)

What I've done is with 6.6 still installed, edited `/etc/dnf/dnf.conf`, and changed the value of `installonly_limit` to 0. This means my fedora machine is adding more kernels automatically but not removing the last 6.6 version. I can manually remove older 6.7.x kernels so I then have a choice in grub to still boot into 6.6.x or 6.7.x

Once this is fixed I'll set that back to 3 again.

**Comment by fabiang** [comment]
For those who update their Fedora system through cli, you can exclude updating the kernel with `dnf up -x 'kernel*'`

**Comment by d4r1us-drk** [comment]
In fedora I just followed these instructions using `koji` to downgrade the kernel to 6.6.14
https://discussion.fedoraproject.org/t/downgrading-to-a-previous-kernel-version/72820

**Comment by w-ko** [comment]
The image has been updated:
2022-latest 	amd64 	No Dockerfile 	Ubuntu 22.04 	05/31/2022 	03/14/2024
latest 	amd64 	No Dockerfile 	Ubuntu 22.04 	09/21/2018 	03/14/2024

It works for me again on Fedora 6.7.9-200.fc39.x86_64

**Comment by fbrosseau** [comment]
Hello,

Yes, sql22cu12 shipped today and it has the fix. The reason fixes are usually blurry on delivery dates and/or CU numbers is that schedules can shift (such as for making room for an urgent security fix, etc). SQL Server Linux follows the release cadence of SQL Server as a whole, and this schedule is quite rigid.

Sql19 will also be fixed for this in its next CU (their release schedules typically each alternate monthly). However sql17 will not, as sql17 is out of mainstream support and only receives security fixes. No bug fixes qualify for sql17.

**Comment by lateparty** [comment]
The merge is great news, was tracking that overnight. Any rough eta from merge to release available to pull down through the Bitwarden.sh? I gave it a shot about an hour ago and no luck yet

**Comment by Drezir** [comment]
Using Fedora 39, only tag 2022-CU12-ubuntu-22.04 works for me, not latest or 2022-latest.

**Comment by felixSabatie** [comment]
2022-latest works fine for me on Fedora 39 with kernel v 6.7.9-200.fc39.x86_64

**Comment by Drezir** [comment]
> 2022-latest works fine for me on Fedora 39 with kernel v 6.7.9-200.fc39.x86_64

I agree, I had to delete locally cached version :)

**Comment by andros0689** [comment]
> 2022-latest works fine for me on Fedora 39 with kernel v 6.7.9-200.fc39.x86_64

Same here. Thanks a lot.

**Comment by thomasvm** [comment]
2022-latest works perfectly on `6.8.1-arch1-1`

**Comment by sergiuser1** [comment]
Not exactly related to the issue, but I upgrade to `2022-latest` from `2019-latest` and now I get the following error when I connect from a .NET core application:
```
 Login failed for user 'sa'. Reason: An error occurred while evaluating the password.
 ```
 The password specified in the `MSSQL_SA_PASSWORD` env variable is the same as the one in the app, and the logs from it are:
 ```
 Microsoft.Data.SqlClient.SqlException (0x80131904): Login failed for user 'sa'.
 ```
 Has anyone had the same issue?

**Comment by sergiuser1** [comment]
> Not exactly related to the issue, but I upgrade to `2022-latest` from `2019-latest` and now I get the following error when I connect from a .NET core application:
> 
> ```
>  Login failed for user 'sa'. Reason: An error occurred while evaluating the password.
> ```
> 
> The password specified in the `MSSQL_SA_PASSWORD` env variable is the same as the one in the app, and the logs from it are:
> 
> ```
> Microsoft.Data.SqlClient.SqlException (0x80131904): Login failed for user 'sa'.
> ```
> 
> Has anyone had the same issue?

Turns out it was a race condition, and MSSQL was simply not completely up yet. I've added a healthcheck to it, and waiting for `service_healthy` before starting the .NET app fixes it.

**Comment by sergiuser1** [comment]
> > Not exactly related to the issue, but I upgrade to `2022-latest` from `2019-latest` and now I get the following error when I connect from a .NET core application:
> > ```
> >  Login failed for user 'sa'. Reason: An error occurred while evaluating the password.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The password specified in the `MSSQL_SA_PASSWORD` env variable is the same as the one in the app, and the logs from it are:
> > ```
> > Microsoft.Data.SqlClient.SqlException (0x80131904): Login failed for user 'sa'.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Has anyone had the same issue?
> 
> Hi @sergiuser1
> 
> No, I don't have that error but I still using SA_PASSWORD, not MSSQL_SA_PASSWORD

That's deprecated according to Microsoft: https://learn.microsoft.com/en-us/sql/linux/quickstart-install-connect-docker?view=sql-server-2017&tabs=cli&pivots=cs1-bash#run-the-container

**Comment by rubnogueira** [comment]
Can you backport the 2022-latest fix but for azure-sql-edge v1? I'm using that version because I need arm64 support, which is currently deprecated in v2, and I can't use it anymore.

**Comment by toxik** [comment]
an `azure-sql-edge` `v1.0.8` arm64 with the patch would be very much appreciated!

**Comment by JimMoen** [comment]
> The image has been updated: 2022-latest amd64 No Dockerfile Ubuntu 22.04 05/31/2022 03/14/2024 latest amd64 No Dockerfile Ubuntu 22.04 09/21/2018 03/14/2024
> 
> It works for me again on Fedora 6.7.9-200.fc39.x86_64

Yes. the fix included in 2022-CU12
change log:
https://learn.microsoft.com/en-us/troubleshoot/sql/releases/sqlserver-2022/cumulativeupdate12#2958874

Unfortunately, SQL Server 2019 havn't release a new cumulative-update with the fix.

**Comment by leonardohtorres** [comment]
For me, I had to use MSSQL 2022 image instead 2019 and then everything worked (Of course previously, I got the last backup from the databases and restored it to the MSSQL 2022).

**Comment by Marcosdg3** [comment]
Are there any plans for a SQL Server 2019 release?

**Comment by Marcosdg3** [comment]
> Are there any plans for a SQL Server 2019 release?

Looks like this has been fixed released in `2019-CU26-ubuntu-20.04` which is now `2019-latest`.

Table here hasn't been updated here yet https://hub.docker.com/_/microsoft-mssql-server/ but checked the tag list and saw the new release (https://mcr.microsoft.com/v2/mssql/server/tags/list). All is working great now on macos, thank you!

**Comment by hockdudu** [comment]
I can confirm that the latest version of `2019-latest` resolved the issue, tested on Fedora with Linux 6.8.7.

**Comment by MPavleski** [comment]
Also confirming that 2019-latest resolved the issue under Linux 6.8.7, tested on Arch.

**Comment by Domgru** [comment]
> an `azure-sql-edge` `v1.0.8` arm64 with the patch would be very much appreciated!

[Downgrading the kernel](https://askubuntu.com/questions/1404722/downgrade-kernel-for-ubuntu-22-04-lts) to v6.6.4 helped for me. But v1.0.8 would be great.

**Comment by beikov** [comment]
Running into the same problem with the 2017 image when upgrading to Fedora 40 which comes with kernel 6.8. Please release a fixed docker image for the 2017 version. We need that for testing in Hibernate ORM.

**Comment by kelkmere** [comment]
This problem just happens to my AWS EC2 Ubuntu 22.04 instance. I fixed it by downgrading the kernel from 6.8.0-1015-aws to 6.5.0-1014-aws. Here's the instruction: https://discourse.ubuntu.com/t/how-to-downgrade-the-kernel-on-ubuntu-20-04-to-the-5-4-lts-version/26459

**Comment by Illutax** [comment]
It happened also on my AWS EC2 Ubuntu 22.04.

We fixed it by updating the MSSQL Image from
mcr.microsoft.com/mssql/server:2019-CU13-ubuntu-20.04
to
mcr.microsoft.com/mssql/server:2019-CU28-ubuntu-20.04

**Comment by martin-schulze-e2m** [comment]
> > Are there any plans for a SQL Server 2019 release?
> 
> Looks like this has been fixed in `2019-CU26-ubuntu-20.04` release which is now `2019-latest`.
> 
> Table here hasn't been updated here yet https://hub.docker.com/_/microsoft-mssql-server/ but checked the tag list and saw the new release (https://mcr.microsoft.com/v2/mssql/server/tags/list). All is working great now on macos, thank you!

I just found 2017-latest to be updated on 2024-10-07 in https://hub.docker.com/_/microsoft-mssql-server/ and it is working again.

**Comment by jcompagner** [comment]
this week i upgraded and restart my ubuntu  22.04.5 LTS and i noticed that the kernel did go from: 6.5.0-1024-aws to 6.8.0-1015-aws. After restart the sqlserver 2022 didn't work anymore
We did a pull of all the latest versions of that or specific CU's (like 12,13 or the latest) but none of them work.
But in these comments it is said that it is fixed but why do we still get:

`
This program has encountered a fatal error and cannot continue running at Wed Sep 25 20:20:18 2024
The following diagnostic information is available:

         Reason: 0x00000001
         Signal: SIGABRT - Aborted (6)
          Stack:
                 IP               Function
                 ---------------- --------------------------------------
                 00005e170c63ca61 std::__1::bad_function_call::~bad_function_call()+0x97ab1
                 00005e170c63c426 std::__1::bad_function_call::~bad_function_call()+0x97476
                 00005e170c63b9af std::__1::bad_function_call::~bad_function_call()+0x969ff
                 0000702c8cb12520 __sigaction+0x50
                 0000702c8cb669fc pthread_kill+0x12c
                 0000702c8cb12476 raise+0x16
                 0000702c8caf87f3 abort+0xd3
                 00005e170c63b88e std::__1::bad_function_call::~bad_function_call()+0x968de
                 00005e170c5ce351 std::__1::bad_function_call::~bad_function_call()+0x293a1
                 00005e170c5ced5d std::__1::bad_function_call::~bad_function_call()+0x29dad
                 00005e170c59879b std::__1::basic_stringbuf<char, std::__1::char_traits<char>, std::__1::allocator<char>>::str() const+0xc7fb
                 00005e170c57acfc <unknown>
                 0000702c8caf9d90 __libc_init_first+0x90
  
`

for all releases of 2022 that we try to use?

**Comment by tobiajo** [comment]
What is causing the issue?

**Comment by danarj** [comment]
I'm having the same issue after upgrading the kernel to 6.8.0 now I don't have any work around

**Comment by Illutax** [comment]
> What is causing the issue?

An Linux kernel update. Now older mssql docker images can't be run successfully. Try updating the docker image to an newer release.

**Comment by jcompagner** [comment]
> > What is causing the issue?
> 
> An Linux kernel update. Now older mssql docker images can't be run successfully. Try updating the docker image to an newer release.

But we tried the latest of a 2022 build , and none work anymore on our machine that runs ubuntu 2022.04 LTS with kernen 6.8

**Comment by Illutax** [comment]
> This is happening for my local ubuntu 22.04.5 with kernel - Linux version 6.8.0-40-generic, when I am trying to build the docker image from the compose file, i am getting similar error -
> 
> this is my base image for sql server - FROM mcr.microsoft.com/mssql/server:2017-CU24-ubuntu-16.04
> 
> **This program has encountered a fatal error and cannot continue running at Mon Sep 30 13:46:01 2024 mssql-prof` | The following diagnostic information is available: mssql-prof | mssql-prof | Reason: 0x00000001 mssql-prof | Signal: SIGABRT - Aborted (6) mssql-prof | Stack: mssql-prof | IP Function mssql-prof | ---------------- -------------------------------------- mssql-prof | 00005f74251cbc35 mssql-prof | 00005f74251cb6c2 mssql-prof | 00005f74251cac11 mssql-prof | 00007af8dcb094c0 killpg+0x40 mssql-prof | 00007af8dcb09438 gsignal+0x38 mssql-prof | 00007af8dcb0b03a abort+0x16a mssql-prof | 00005f7425131fed mssql-prof | 00005f74251d7714 mssql-prof | 00005f74251fbd98 mssql-prof | 00005f74251fbb10 mssql-prof | 00005f74251408f4 mssql-prof | 00005f7425140489 mssql-prof | Process: 12 - sqlservr mssql-prof | Thread: 84 (application thread 0x138) mssql-prof | Instance Id: 252bbfb1-44a3-446a-b822-1c1f310459a2 mssql-prof | Crash Id: 1e0024a2-d6c5-499a-b853-4fbc68acb9e3 mssql-prof | Build stamp: 23b9dfd98170ce033c3334f80ad499e84f504fec8d90876c718146f04b79943f mssql-prof | Distribution: Ubuntu 16.04.7 LTS mssql-prof | Processors: 12 mssql-prof | Total Memory: 33463422976 bytes mssql-prof | Timestamp: Mon Sep 30 13:46:01 2024 mssql-prof | Last errno: 2 mssql-prof | Last errno text: No such file or directory mssql-prof | Executing: /opt/mssql/bin/handle-crash.sh with parameters mssql-prof | handle-crash.sh mssql-prof | /opt/mssql/bin/sqlservr mssql-prof | 12 mssql-prof | /opt/mssql/bin mssql-prof | /var/opt/mssql/log/ mssql-prof | mssql-prof | 252bbfb1-44a3-446a-b822-1c1f310459a2 mssql-prof | 1e0024a2-d6c5-499a-b853-4fbc68acb9e3 mssql-prof | mssql-prof | mssql-prof | Ubuntu 16.04.7 LTS mssql-prof | Capturing core dump and information to /var/opt/mssql/log... mssql-prof | dmesg: read kernel buffer failed: Operation not permitted mssql-prof | No journal files were found. mssql-prof | No journal files were found. mssql-prof | Mon Sep 30 13:46:01 UTC 2024 Capturing program information mssql-prof | Mon Sep 30 13:46:02 UTC 2024 Attempting to capture a dump with paldumper for pid 12 mssql-prof | Captured a dump with paldumper mssql-prof | Mon Sep 30 13:46:02 UTC 2024 Capturing program binaries mssql-prof | Mon Sep 30 13:46:02 UTC 2024 Compressing the dump files**

Try 2017-CU31-GDR2-ubuntu-18.04

**Comment by 005Dikshant** [comment]
i downgrade from 6.8.0-40 generic to 6.5.0.41-generic now it is working again for my local system.

**Comment by alex-jitbit** [comment]
This is not an issue with Docker, but a much bigger issue with MSSQL itself. Upgrading kernel on my AWS instances is not causing mssql to fail with this exact same error (under kernel 6.8.0). Booting to an older kernel (6.5.0-101`7) resolves the issue.

**Comment by electricstrm-redgate** [comment]
We have the same problem on azure VMs kernel 6.8.0-1015-azure and image 
http://mcr.microsoft.com/mssql/server:2022-CU8-ubuntu-20.04

**Comment by dfurmans** [comment]
We have the same issue in our team. Would be great to address it 🙏🏽

**Comment by longlifeisland** [comment]
> We have the same problem on azure VMs kernel 6.8.0-1015-azure and image http://mcr.microsoft.com/mssql/server:2022-CU8-ubuntu-20.04

We also had this problem on azure (with 2017-CU31-GDR2-ubuntu-18.04 and 2017-latest docker images), but we resolved it by downgrading to Kernel 6.5.0-1022-azure. I suppose there's nothing more to say, just wanted to add that it's also works with azure type images. :)

**Comment by rodubero** [comment]
Seems like the 2019-CU30-ubuntu-20.04 image can handle it with kernel 6.8.0, but in this new version the path for sqlcmd changed from `/opt/mssql-tools/bin/sqlcmd` to `/opt/mssql-tools18/bin/sqlcmd`  :D

**Comment by haikn** [comment]
May not be the same but I had this issue
-----------------------------
Macbook pro M2 - Sequoia 15.6
Docker desktop: 4.44.3 (202357)
docker run -d --name mssql -e 'ACCEPT_EULA=Y' -e 'mypassword' -p 1433:1433 mcr.microsoft.com/azure-sql-edge
-----------------------------
Reason: 0x00000001
         Signal: SIGABRT - Aborted (6)
          Stack:
                 IP               Function
                 ---------------- --------------------------------------
                 0000aaaab816ba70 std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::~_Sp_counted_base()+0x25d0
                 0000aaaab816b618 std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::~_Sp_counted_base()+0x2178
                 0000aaaab816ad1c std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::~_Sp_counted_base()+0x187c
                 0000ffffa86b47a0 <unknown>
                 0000ffffa7f9d598 raise+0xb0
                 0000ffffa7f9e974 abort+0x154
                 0000aaaab816f60c std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::~_Sp_counted_base()+0x616c
                 0000aaaab822e210 std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > std::operator+<char, std::char_traits<char>, std::allocator<char> >(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_
                 0000ffffa4298288 S_SbtUnimplementedInstruction+0x275744
                 0000ffffa4285d4c S_SbtUnimplementedInstruction+0x263208
                 0000ffffa42c7658 S_SbtUnimplementedInstruction+0x2a4b14
                 0000ffffa42b7324 S_SbtUnimplementedInstruction+0x2947e0
                 0000ffffa42b65d4 S_SbtUnimplementedInstruction+0x293a90
                 0000ffffa42b89c8 S_SbtUnimplementedInstruction+0x295e84
                 0000ffffa42785d4 S_SbtUnimplementedInstruction+0x255a90
                 0000ffffa40d5150 S_SbtUnimplementedInstruction+0xb260c
                 0000ffffa40ee72c S_SbtUnimplementedInstruction+0xcbbe8
                 0000ffffa40eea4c S_SbtUnimplementedInstruction+0xcbf08
                 0000ffffa40298d4 S_SbtUnimplementedInstruction+0x6d90
                 0000ffffa42fc538 S_SbtUnimplementedInstruction+0x2d99f4
                 0000ffff9df0cfac S_SbtUnimplementedInstruction+0xc28cc
                 0000ffff844df2ec S_SbtUnimplementedInstruction+0xa48ec
                 0000ffff844dd018 S_SbtUnimplementedInstruction+0xa2618

**Comment by beikov** [comment]
I just upgraded to Kernel 6.17.9 and wanted to say that the 2017 image seems to be working.
