### ISSUE TITLE
[2025-latest] Container crashes on macOS 26 (Tahoe)

### ISSUE THREAD

**Issue by wiruzman** [Microsoft/mssql-docker#942]
macOS 26 (Tahoe) is stable live, but mssql 2025 docker image does fail to start with following log output:
```
SQL Server 2025 will run as non-root by default.
This container is running as user mssql.
To learn more visit https://go.microsoft.com/fwlink/?linkid=2099216.
assertion failed [x86_avx_state_ptr->xsave_header.xfeatures == kSupportedXFeatureBits]: 
(ThreadContextSignals.cpp:414 rt_sigreturn)
```

The container started with following command:
`docker run -e 'ACCEPT_EULA=Y' -e 'SA_PASSWORD=Str0ng!Passw0rd' -p 1433:1433 --platform linux/amd64 mcr.microsoft.com/mssql/server:2025-latest`

OS: macOS 26
Docker Desktop version: 4.44.3 with rosetta and Apple virtualization

Workaround: mssql 2022 still works.

**Comment by osbeorn** [comment]
I get the same error, which I reported [here](https://github.com/microsoft/mssql-docker/issues/940#issuecomment-3318391005).

**Comment by wiruzman** [comment]
> I get the same error, which I reported [here](https://github.com/microsoft/mssql-docker/issues/940#issuecomment-3318391005).

@osbeorn I know, but the issue had a different symptom, so I thought a separate issue would be more visible.

**Comment by gregpakes** [comment]
Did anyone figure out any work arounds?

**Comment by ArnoZeelmaekers** [comment]
We're having the exact same issue. Also doesn't help that .NET Aspire 9.5 now defaults to 2025-latest causing all MacOS ARM development to break. Created a linked issue there [#11736](https://github.com/dotnet/aspire/issues/11736)

**Comment by mattleibow** [comment]
Aspire rolled back: https://github.com/dotnet/aspire/issues/11736

But now I would like to use vectors which are 2025-only. So yeah, sad days.

**Comment by TaylorWatson** [comment]
You know what's hilarious. If you install Parallels you can get SQL Server 2025 running on a Windows Arm install.

So let's review the scoreboard.

- 4 trillion dollar company who creates their own Arm64 laptops custom built for their own Arm64 OS ❌
- 800 employee private german company developing for a competitor OS ✅

We're angry because we care. Please do not force our hands to move away from MSSQL.

**Comment by wesleyteixeira** [comment]
I’m migrating from a MacBook Pro M2 to a MacBook Pro M3, and I can confirm that the problem only happens on the new machine.
	•	On the M2, running macOS Sequoia 15.6.1, the image mcr.microsoft.com/mssql/server:2025-latest works normally
	•	On the M3, running macOS Tahoe 26.1, the same image fails to start with the exact error reported in this issue

**Comment by aadvandenhoogenband** [comment]
Initially had the same error on M4 Tahoe `26.1` and docker version `27.5.1`. Issue seems resolved after I updated docker to `28.x`.

**Comment by wesleyteixeira** [comment]
Here I'm using Docker Engine: 29.0.1

**Comment by jvalkeejarvi** [comment]
I get exactly the same error as described in the issue. Using Docker 28.x on M4 Macbook Pro and MacOS 26.1.

**Comment by TaylorWatson** [comment]
> Initially had the same error on M4 Tahoe `26.1` and docker version `27.5.1`. Issue seems resolved after I updated docker to `28.x`.

<img width="2284" height="872" alt="Image" src="https://github.com/user-attachments/assets/fa2f1e9e-6c46-4541-89c3-c7e8c6638172" />

I am very curious how you have gotten around this when none of us can, are you doing something unique?

**Comment by aadvandenhoogenband** [comment]
Not sure if I'm doing something unique. I just ran the following command locally:
`docker run -e "ACCEPT_EULA=Y" -e "MSSQL_SA_PASSWORD=<password>" -p 1433:1433  --name sqlpreview --hostname sqlpreview --platform=linux/amd64 -d mcr.microsoft.com/mssql/server:2025-latest`.

Did have to specifically add the platform, because there is no ARM based image of course. Maybe check if rosetta is enabled. Besides that I really have no clue what im doing differently.

**Comment by ZeroThe2nd** [comment]
Currently running:
- macOS 26.1
- Rosetta 2 (installed)
- OrbStack v2.0.5
- Docker version 28.5.2, build `ecc6942`
- `mssql/server:2025-latest` with creation date: `25 Oct 2025 at 2:01`

The image does seem to work (with the exact command specified by @aadvandenhoogenband ). Omitting the `--platform` flag simply causes an error that no image for the architecture is available. So it _might_ have been fixed with a newer Docker engine version.

While I'm happy it seems to work now, we're still not sure if this is because of the docker engine, or something else. Can someone who may still have an older version installed (maybe, please?) confirm if Docker@<28.x doesn't work?

Also, this doesn't mean we wouldn't still love to see a compatible arm64 image. Even if only for (as pointed out [earlier](https://github.com/microsoft/mssql-docker/issues/942#issuecomment-3530382480)) the sake of supporting their own platform.

**Comment by wilbert-nl** [comment]
I am using docker 29 on Mac M4, macOS 26.1, and still got the same error mentioned on https://github.com/microsoft/mssql-docker/issues/942#issue-3441374412.

I even tried the command on https://github.com/microsoft/mssql-docker/issues/942#issuecomment-3574158864. but still got the error.

**Comment by wesleyteixeira** [comment]
I wanted to add one more data point.

After reading the steps described here:
https://www.nocentino.com/posts/2025-11-26-sql-server-2025-docker-desktop-avx-issue/

I installed OrbStack (latest version) on my MacBook Pro M3 running macOS 26.1 and tested the exact same `2025-latest` image — and surprisingly, it works there without the AVX/xsave assertion failure.

So in my case:

**Docker Desktop (Engine 28.x or 29.x) → crash**  
**OrbStack → works normally**

**Comment by juniocezar** [comment]
> I wanted to add one more data point.
> 
> After reading the steps described here: https://www.nocentino.com/posts/2025-11-26-sql-server-2025-docker-desktop-avx-issue/
> 
> I installed OrbStack (latest version) on my MacBook Pro M3 running macOS 26.1 and tested the exact same `2025-latest` image — and surprisingly, it works there without the AVX/xsave assertion failure.
> 
> So in my case:
> 
> **Docker Desktop (Engine 28.x or 29.x) → crash** **OrbStack → works normally**

For now, I am going with **OrbStack** as well. I was able to run the sqlserver image now (previously breaking with Docker Desktop and Colima)

Environment:
* macOS Tahoe 26.1
```
docker image ls
REPOSITORY                       TAG           IMAGE ID       CREATED       SIZE
mcr.microsoft.com/mssql/server   2025-latest   55c3fe0f8428   6 weeks ago   1.79GB
```

```
docker context ls
NAME            DESCRIPTION                               DOCKER ENDPOINT                                     ERROR
default         Current DOCKER_HOST based configuration   unix:///var/run/docker.sock                         
desktop-linux   Docker Desktop                            unix:///Users/<user>/.docker/run/docker.sock     
orbstack *      OrbStack                                  unix:///Users/<user>/.orbstack/run/docker.sock   
```

```
docker logs -f sqlserver
SQL Server 2025 will run as non-root by default.
This container is running as user mssql.
To learn more visit https://go.microsoft.com/fwlink/?linkid=2099216.
2025-12-08 14:13:44.14 Server      Setup step is copying system data file 'C:\templatedata\master.mdf' to '/var/opt/mssql/data/master.mdf'.
2025-12-08 14:13:44.17 Server      Did not find an existing master data file /var/opt/mssql/data/master.mdf, copying the missing default master and other system database files. If you have moved the database location, but not moved the database files, startup may fail. To repair: shutdown SQL Server, move the master database to configured location, and restart.
2025-12-08 14:13:44.17 Server      Setup step is copying system data file 'C:\templatedata\mastlog.ldf' to '/var/opt/mssql/data/mastlog.ldf'.
2025-12-08 14:13:44.17 Server      Setup step is copying system data file 'C:\templatedata\model.mdf' to '/var/opt/mssql/data/model.mdf'.
2025-12-08 14:13:44.17 Server      Setup step is copying system data file 'C:\templatedata\modellog.ldf' to '/var/opt/mssql/data/modellog.ldf'.
2025-12-08 14:13:44.18 Server      Setup step is copying system data file 'C:\templatedata\msdbdata.mdf' to '/var/opt/mssql/data/msdbdata.mdf'.
2025-12-08 14:13:44.19 Server      Setup step is copying system data file 'C:\templatedata\msdblog.ldf' to '/var/opt/mssql/data/msdblog.ldf'.
2025-12-08 14:13:44.19 Server      Setup step is FORCE copying system data file 'C:\templatedata\model_replicatedmaster.mdf' to '/var/opt/mssql/data/model_replicatedmaster.mdf'.
2025-12-08 14:13:44.20 Server      Setup step is FORCE copying system data file 'C:\templatedata\model_replicatedmaster.ldf' to '/var/opt/mssql/data/model_replicatedmaster.ldf'.
2025-12-08 14:13:44.20 Server      Setup step is FORCE copying system data file 'C:\templatedata\model_msdbdata.mdf' to '/var/opt/mssql/data/model_msdbdata.mdf'.
2025-12-08 14:13:44.21 Server      Setup step is FORCE copying system data file 'C:\templatedata\model_msdblog.ldf' to '/var/opt/mssql/data/model_msdblog.ldf'.
2025-12-08 14:13:44.23 Server      Microsoft SQL Server 2025 (RTM) - 17.0.1000.7 (X64) 
	Oct 21 2025 12:05:57 
	Copyright (C) 2025 Microsoft Corporation
	Enterprise Developer Edition (64-bit) on Linux (Ubuntu 22.04.5 LTS) <X64>
2025-12-08 14:13:44.23 Server      UTC adjustment: 0:00
...
```

**Comment by gregpakes** [comment]
Thanks for the Orbstack recommendation - I have switched and it works great.

**Comment by shakibstu** [comment]
OrbStack not free though

**Comment by wiruzman** [comment]
An update: Microsoft silently updated something on `2025-latest` tag. When checking [here](https://hub.docker.com/r/microsoft/mssql-server#full-tag-listing), the latest update for `2025-latest` is 09/16/2025. The latest update for `2025-RC1-ubuntu-x` is also 09/16/2025, so I was thinking the bug was still active to not work on macOS. However checking the image creation date in Docker Desktop, `2025-latest` has the date 01/09/2026 and all other images are from 2025 (see screenshot). I tested all non-`2025-latest`, they all fail.

Tag list:
<img width="990" height="323" alt="Image" src="https://github.com/user-attachments/assets/16da5515-6bc2-42cc-bcb3-f2c5306784f8" />

Image list in Docker Desktop:
<img width="792" height="370" alt="Image" src="https://github.com/user-attachments/assets/e79f8398-f0f3-4231-ab22-793cf79f2c36" />

Can anyone confirm that the `2025-latest` image is working?

**Comment by gregpakes** [comment]
As far as I know, there is no evidence that the 2025-latest tag works on Tahoe in Docker Desktop.  It works in Orbstack, but not Docker Desktop.

From my understanding, the fix would need to come in the form of a Docker update, not a SQL image update.

SQL 2025 requires AVX CPU instructions, which the Rosetta 2 emulation layer does not provide in Docker Desktop.

**Comment by wiruzman** [comment]
@gregpakes `2025-latest` does work for me on Docker Desktop 4.46.0+.

**Comment by gregpakes** [comment]
> @gregpakes `2025-latest` does work for me on Docker Desktop 4.46.0+.

I'll test and report back

Update: Seems to work for me too... was it officially fixed at a SQL level then?

**Comment by wiruzman** [comment]
I only tested on machines that had OrbStack installed previously. I tried clean up OrbStack, but I am not sure if any residues would have an effect on Docker Desktop.

**Comment by nocentino** [comment]
Some how during start up SQL Server is reporting access to AVX capabilities when using 2025 CU1 on Docker Version 4.56.0 (214940). 

2026-01-16 21:57:46.91 Server      CPU vectorization level(s) detected:  SSE SSE2 SSE3 SSSE3 SSE41 SSE42 AVX AVX2 POPCNT BMI1 BMI2

RTM still crashes when it hits the check for CPU's AVX capabilities on Docker Version 4.56.0 (214940).

**Comment by PsyChonek** [comment]
It was working for me until today :/ Docker v28.1.1. 

Only thing that changed looks to be https://packages.microsoft.com/ubuntu.

~~Also what version of Ubuntu should I use? 2025-latest osVersion shows 22.04 but RC is on 24, I had issues with fulltext (missing libldap and unable to install due version mismatch even mssql22 has no issue).~~

Thanks

**Comment by gregpakes** [comment]
Its still working on mine:

Docker Desktop: v4.55.0
Docker Engine: v29.1.3

**Comment by talksinmath** [comment]
did not work for me.

Desktop Version: 4.57
 Version:    29.1.3

**Comment by anvar-ramazanov** [comment]
It doesn't work for me: 
image: mcr.microsoft.com/mssql/server:2025-latest
docker engine version: 29.1.3
docker desktop: 4.57.0 (215387)
macos: 26.2 (25C56)

**Comment by gregpakes** [comment]
Is mine working because I installed Orbstack and then uninstalled it?

**Comment by nocentino** [comment]
CU1 has been pulled back due to a bug with Database Mail. The Latest tag currently points to the RTM, which does not include the AVX fixes. Once CU1 is re-released, I believe the Docker issues will be resolved. Orbstack should function as expected, but folks using Docker will need to wait for the re-release of CU1.

**Comment by asjafjell** [comment]
We had a running database using the image `mcr.microsoft.com/mssql/server:2025-latest` from January 8 on `macOS 26`. Updating images in Docker yesterday replaced it with an image from three months ago. The original image had the ID `sha256:0d0a3b783eedc47d1acc4ea04854775392979680b8f176874ff735638c345377`, but it no longer appears to be available.

Thanks for the update and the additional context, @nocentino. Where did you find this information? Fingers crossed this will be fixed quickly. This is a good reminder of why pinning images by `sha256` is safer than relying on latest

**Comment by c4l3b** [comment]
I was just able to pull mcr.microsoft.com/mssql/server:2025-latest on my M2 MBP (Tahoe) and successfully start a container! (Rosetta, but still...) 🥳 

Docker Desktop 4.58.1
Docker Engine 29.1.5

`SELECT @@VERSION AS 'SQL Server Version';`

```
Microsoft SQL Server 2025 (RTM-CU1) (KB5078298) - 17.0.4006.2 (X64) 
	Jan 22 2026 18:05:52 
	Copyright (C) 2025 Microsoft Corporation
	Enterprise Developer Edition (64-bit) on Linux (Ubuntu 24.04.3 LTS) <X64>
```

**Comment by nocentino** [comment]
Yes, CU1 was re-released yesterday and the latest tag updated to point to it - https://mcr.microsoft.com/en-us/artifact/mar/mssql/server/tags

**Comment by wiruzman** [comment]
I have tested 2025-latest tag and it is working. I think we can close this issue.

**Comment by matthetherington** [comment]
Just in case anyone else doesn't have their head screwed on, I'd tried this before with the old broken image, so I had to first remove that:

```
docker rmi mcr.microsoft.com/mssql/server:2025-latest
```

Then start a new container:

```
docker run -e "ACCEPT_EULA=Y" -e "MSSQL_SA_PASSWORD=REDACTED" \
   -p 1433:1433 --name mssqlcontainer2025 --hostname mssqlcontainer2025 --platform=linux/amd64 \
   -d mcr.microsoft.com/mssql/server:2025-latest
```

and that's now working fine! Thank you to all those responsible, that's been a headache for years.
